### ISSUE TITLE
Contributte docs + QA + style

### ISSUE THREAD

**Issue by f3l1x** [contributte/newrelic#18]

**Comment by f3l1x** [comment]
ping @foxycode

**Comment by foxycode** [comment]
Will look into it :)

**Comment by f3l1x** [comment]
ping @foxycode

**Comment by foxycode** [comment]
50% complete

**Comment by f3l1x** [comment]
Please take a look at:

- README: https://github.com/contributte/monolog/blob/b521d0329faa4e6ea3dc7e97eff9de4deb09e748/README.md
- Makefile (instead of composer scripts): https://github.com/contributte/monolog/blob/b521d0329faa4e6ea3dc7e97eff9de4deb09e748/Makefile
- Editorconfig: https://github.com/contributte/monolog/blob/b521d0329faa4e6ea3dc7e97eff9de4deb09e748/.editorconfig
- gitignore: https://github.com/contributte/monolog/blob/b521d0329faa4e6ea3dc7e97eff9de4deb09e748/.gitignore
- gitattributes: https://github.com/contributte/monolog/blob/b521d0329faa4e6ea3dc7e97eff9de4deb09e748/.gitattributes

**Comment by f3l1x** [comment]
Any progress @foxycode?

**Comment by foxycode** [comment]
Done
