### ISSUE TITLE
Undefined index: rum

### ISSUE THREAD

**Issue by patrickkusebauch** [contributte/newrelic#19]
Verze: 8.0.0

Podle dokumentace je config `rum` optional. Pokud ho ovšem ale v nezadám, tak dostanu `notice - Undefined index: rum` o odkazem na tento řádek v masteru:
https://github.com/contributte/newrelic/blob/db0970e97a48b1679930eb95fa2c5613e084bf5f/src/DI/NewRelicExtension.php#L236

Tracy "Bluescreen":
![Screenshot from 2020-11-22 02-36-00](https://user-images.githubusercontent.com/1620948/99891569-905bf300-2c6b-11eb-9d09-5ea0cc7b862e.png)

PS: Je možné, že to je kompandováno změnou namespace. Bylo by super vydat tag v tomto novém namespace. Zkusil jsem instalovat podle master dokumentace a byl jsem velice nemile překvapen.

**Comment by foxycode** [comment]
@patrickkusebauch Můžeš prosím vyzkoušet kód z https://github.com/contributte/newrelic/pull/20 zda funguje jak má?

**Comment by patrickkusebauch** [comment]
@foxycode Ahoj, promiň za prodlevu.

Vyzkoušel jsem tu větev - schema funguje.

Nicméně to není kompatibilní s Tracy:
![Screenshot from 2020-12-11 11-31-24](https://user-images.githubusercontent.com/1620948/101893049-7cd5e500-3ba4-11eb-80aa-6a5cbeb4c53b.png)
![Screenshot from 2020-12-11 11-31-44](https://user-images.githubusercontent.com/1620948/101893051-7d6e7b80-3ba4-11eb-80aa-0fc8ef69df51.png)

Myslím si, že víc k tomu není potřeba dodat.

**Comment by foxycode** [comment]
@patrickkusebauch Can you please try now?

**Comment by patrickkusebauch** [comment]
:+1: **LGTM**

**Comment by foxycode** [comment]
@patrickkusebauch Try with master please and I make new release after.

**Comment by patrickkusebauch** [comment]
:+1: **LGTM** @foxycode for master
