### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by f3l1x** [contributte/newrelic#27]
Take a look at other contributte repo, codecoverage is really simple via coveralls. :-)

**Comment by foxycode** [comment]
@f3l1x Can you create token for me and allow sonarcloud for this repo too?

**Comment by f3l1x** [comment]
Repo created on sonarcloud. Just push something. :-)

**Comment by foxycode** [comment]
@f3l1x Any ideas?
https://github.com/contributte/newrelic/runs/2086736582?check_suite_focus=true

**Comment by f3l1x** [comment]
No idea, does it work on localhost?

**Comment by foxycode** [comment]
```bash
> vendor/bin/tester -s -p phpdbg -C --coverage ./coverage.xml --coverage-src ./src tests/Cases
PHP Warning:  Module 'newrelic' already loaded in Unknown on line 0
 _____ ___  ___ _____ ___  ___
|_   _/ __)( __/_   _/ __)| _ )
  |_| \___ /___) |_| \___ |_|_\  v2.4.0

Code coverage by PHPDBG: /app/coverage.xml
PHP 7.2.34-18+ubuntu18.04.1+deb.sury.org+1 (cli); PHPDBG 0.5.0 | phpdbg -qrrb -S cli | 8 threads

........


OK (8 tests, 0.3 seconds)
Generating code coverage report... 65% covered
```

**Comment by f3l1x** [comment]
Oh I see, test PHP 7.4. ;-) Tests are failing.

**Comment by foxycode** [comment]
Only with code coverage:
https://github.com/contributte/newrelic/runs/2119878818?check_suite_focus=true

Works great on my machine even with php 7.4 and code coverage

**Comment by f3l1x** [comment]
Solved
